export const products = [
    {
        numero_orden: "100001",
        cliente: "Bodega Chandon",
        cantidad: 10000, 
        descripcion: "Etiquetas",
        precio: 100,
        proveedor: "Etiquetas S.A.",
        estado: "Solicitud de Presupuesto",
        estado_id: "1",
        observaciones: "observaciones de la orden con texto mucho más extenso para ver la disposicón en la pantalla",
        numero_plano: "123",
        pie_maquina: "1",
        fecha_entrega: "10/08/2022",
        fecha: "10/06/2022",
        id: 4,
        delay: 4,
        categoria: 'Cajas',
    },
    {
        numero_orden: "100003",
        cliente: "Bodega Nieto Senetiner",
        descripcion: "Botellas",
        cantidad: 15000,
        precio: 400,
        proveedor: "Botellera Mendoza.",
        estado: "Análisis de Factibilidad",
        estado_id: "2",
        pie_maquina: "0",
        fecha_entrega: "10/08/2022",
        fecha: "10/06/2022",
        id: 6,
        delay: 10,
        categoria: 'Botellas',
    },
    {
        numero_orden: "100008",
        cliente: "Bodegas y viñedos Peñaflor",
        descripcion: "Empaques",
        cantidad: 60000,
        precio: 120,
        pie_maquina: "0",
        proveedor: "Etiquetas S.A.",
        estado: "Desarrollo Estructural",
        estado_id: "3",
        fecha_entrega: "05/08/2022",
        fecha: "10/06/2022",
        id: 8,
        delay: 0,
        categoria: 'Cajas',
    },
    {
        numero_orden: "100015",
        cliente: "Luigi Bosca",
        descripcion: "Etiquetas",
        cantidad: 30000,
        precio: 110,
        pie_maquina: "0",
        proveedor: "Etiquetas S.A.",
        estado: "Prototipo Aprobado",
        estado_id: "4",
        fecha_entrega: "25/09/2022",
        fecha: "10/06/2022",
        id: 12,
        delay: 0,
        categoria: 'Etiquetas',
    },
    {
        numero_orden: "100021",
        cliente: "Bodega Chandon",
        descripcion: "Etiquetas edición limitada",
        cantidad: 67000,
        precio: 320,
        pie_maquina: "0",
        proveedor: "Etiquetas S.A.",
        estado: "Pedido de cotización",
        estado_id: "5",
        fecha_entrega: "10/10/2022",
        fecha: "10/06/2022",
        id: 25,
        delay: 14,
        categoria: 'Etiquetas',
    },
    {
        numero_orden: "100022",
        cliente: "Ruca Malen",
        descripcion: "Etiquetas",
        cantidad: 28500,
        precio: 130,
        pie_maquina: "0",
        proveedor: "Etiquetas S.A.",
        estado: "Cotizado",
        estado_id: "6",
        fecha_entrega: "10/08/2022",
        fecha: "10/06/2022",
        id: 40,
        pie_maquina: "0",
        delay: 24,
        categoria: 'Etiquetas',
    },
    {
        numero_orden: "100022",
        cliente: "Finca Las Moras",
        descripcion: "Botellas",
        cantidad: 50000,
        precio: 420,
        pie_maquina: "0",
        proveedor: "Botellera Mendoza",
        estado: "Orden Asignada",
        estado_id: "7",
        fecha_entrega: "10/08/2022",
        fecha: "10/06/2022",
        id: 41,
        delay: 4,
        categoria: 'Botellas',
    },
    {
        numero_orden: "100022",
        cliente: "Chandon",
        descripcion: "Cajas",
        cantidad: 46000,
        precio: 80,
        pie_maquina: "0",
        proveedor: "Cartones SRL",
        estado: "Orden NO Asignada",
        estado_id: "8",
        fecha_entrega: "",
        fecha: "10/06/2022",
        id: 42,
        delay: "",
        categoria: 'Cajas',
    },
    {
        numero_orden: "100024",
        cliente: "Las Moras",
        descripcion: "Etiquetas",
        cantidad: 50000,
        precio: 140,
        pie_maquina: "0",
        proveedor: "Etiquetas S.A.",
        estado: "Proceso Aprobación Diseño",
        estado_id: "9",
        fecha_entrega: "15/09/2022",
        fecha: "10/06/2022",
        id: 44,
        delay: 8,
        categoria: 'Cajas',
    },
    {
        numero_orden: "100025",
        cliente: "Ruca Malen",
        descripcion: "Cajas",
        cantidad: 35000,
        precio: 90,
        pie_maquina: "1",
        proveedor: "Cartones SRL",
        estado: "En Prod. con Pie de Máquina",
        estado_id: "10",
        fecha_entrega: "15/08/2022",
        fecha: "10/06/2022",
        id: 46,
        delay: 12,
        categoria: 'Cajas',
    },
    {
        numero_orden: "100026",
        cliente: "Chandon",
        descripcion: "Cajas",
        cantidad:40000,
        precio: 92,
        pie_maquina: "0",
        proveedor: "Cartones SRL",
        estado: "En Producción",
        estado_id: "11",
        fecha_entrega: "20/07/2022",
        fecha: "10/06/2022",
        id: 47,
        delay: 0,
        categoria: 'Cajas',
    },
    {
        numero_orden: "100026",
        cliente: "Luigi Bosca",
        descripcion: "Etiquetas",
        cantidad:20000,
        precio:160,
        pie_maquina: "0",
        proveedor: "Etiquetas S.A.",
        estado: "Entregado",
        estado_id: "12",
        fecha_entrega: "02/07/2022",
        fecha: "10/06/2022",
        id: 48,
        delay: 4,
        categoria: 'Cajas',
    },
    {
        numero_orden: "100026",
        cliente: "Chandon",
        descripcion: "Cajas",
        cantidad: 40000,
        precio: 98,
        pie_maquina: "1",
        proveedor: "Cartones SRL",
        estado: "Cerrado",
        estado_id: "13",
        fecha_entrega: "01/07/2022",
        id: 49,
        delay: 14,
        categoria: 'Cajas',
    }
    
]